Add ability to specify generated time series file output path
NCAR/CUPiD pull request #117
Opened 2024-07-16 22:06 UTC by nusbaume

Fixes #116 

### All Submissions:

* [ ] Have you followed the guidelines in our Contributer's Guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide) (including the `pre-commit` check)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-07-16 22:18 UTC, nusbaume commented
@mnlevy1981 @TeaganKing please let me know what tests you want to have run with this branch as specified in the checklist above (I obviously tested it in my own config file).  Thanks!

2024-07-17 17:15 UTC, TeaganKing commented
Hi @nusbaume , We don't have robust testing set up yet (that PR template checklist was a bit preemptive), so I think just testing with your own config file is great.

2024-07-17 17:17 UTC, TeaganKing commented
It looks like the pre-commit is also passing.  Whenever it's ready, feel free to request a review.

2024-07-17 20:33 UTC, nusbaume commented
@TeaganKing thanks for letting me know!  Sadly it looks like I am unable to add reviewers to this PR.

2024-07-17 20:47 UTC, mnlevy1981 requested changes
This looks great! Just one small request and then a quick question that will lead to a second small request regardless of your answer :)

2024-07-17 20:47 UTC, mnlevy1981 commented on cupid/run.py
> +                    ]
One suggestion: can we keep `ts_output_dir` as a string, and pass `[ts_output_dir]` to `cupid.timeseries.create_time_series()`? (A separate issue ticket might be to update `create_time_series` to accept strings or lists as arguments, so list-ifying a handful of arguments seems silly... but that will be easier to address if `ts_output_dir` is a string.)

Also, a question: an alternate approach to this block of code would be

```py3
                if "ts_output_dir" in timeseries_params:
                    ts_output_dir =os.path.join(
                        timeseries_params["ts_output_dir"],
                        f"{component}", "proc", "tseries",
                    )
                else:
                    ts_output_dir = os.path.join(
                        global_params["CESM_output_dir"],
                        timeseries_params["case_name"],
                        f"{component}", "proc", "tseries",
                    )
```

Is there a reason to prefer one implementation over the other? If you want to keep

```py3
var=value
if condition:
    var=other_value
```

I see one `if-else` block in `run.py`, could you change that one?

```diff
        # Doing initial subsetting on full catalog, e.g. to only use certain cases

+        cat_path = full_cat_path
        if "subset" in control["data_sources"]:
            first_subset_kwargs = control["data_sources"]["subset"]
            cat_subset = full_cat.search(**first_subset_kwargs)
            # This pulls out the name of the catalog from the path
            cat_subset_name = full_cat_path.split("/")[-1].split(".")[0] + "_subset"
            cat_subset.serialize(
                directory=temp_data_path, name=cat_subset_name, catalog_type="file",
            )
            cat_path = temp_data_path + "/" + cat_subset_name + ".json"
-        else:
-            cat_path = full_cat_path
```

2024-07-17 21:37 UTC, nusbaume commented on cupid/run.py
> +                    ]
I am happy with either method of writing the if-statement.  I personally prefer the `if-else` method, but have found that some static analysis tools like `pylint` will complain about it, hence I went the `var=value, if condition: var=other_value` way in this PR.  Do you all have a preference one way or the other?

2024-07-17 22:06 UTC, mnlevy1981 commented on cupid/run.py
> +                    ]
Let's stick with `if-else`, and if we eventually add `pylint` or some other checker that complains we'll just have one more block to update.

2024-07-17 22:40 UTC, nusbaume commented on cupid/run.py
> +                    ]
Sounds good!  I've applied the requested changes.

2024-07-18 14:57 UTC, mnlevy1981 approved these changes
looks great!

2024-07-18 14:57 UTC, merged