Adding key metrics: Isla's NMSE metric
NCAR/CUPiD pull request #121
Opened 2024-08-05 15:50 UTC by TeaganKing

This PR brings in the NMSE key metrics which @islasimpson created for atm.

This is a useful example of a key metric that could also be used in the diagnostics portion of the CESM tutorial.

--

### All Submissions:
* [x] Have you followed the guidelines in our [Contributor's Guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide) (including the `pre-commit` check)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:
1. [x] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully ran tests with your changes locally?

2024-08-05 16:28 UTC, mnlevy1981 requested changes
I'll wait until you've had a chance to do your final testing before running the notebook myself, though a few cells caught my eye

2024-08-05 16:28 UTC, mnlevy1981 commented on examples/nblibrary/atm/averaging_utils.py
> +    return alldat
Is there a reason to make a local copy before returning?

```py3
return xr.merge([dat_djf, dat_mam, dat_jja, dat_son, dat_am])
```

feels a little cleaner

2024-08-05 16:28 UTC, mnlevy1981 commented on examples/nblibrary/atm/nmse_PSL.ipynb
> +  },
This cell is overwriting the parameters set in the earlier cell

2024-08-05 16:28 UTC, mnlevy1981 commented on examples/nblibrary/atm/nmse_PSL.ipynb
> +   ]
This cell is overwriting `dat`, which was read in earlier

2024-08-05 16:57 UTC, kafitzgerald commented on examples/nblibrary/atm/averaging_utils.py
> +def seasonal_climatology_weighted(dat):
This looks like something we should look into supporting in geocat-comp.  There's already some similar functionality, but I don't believe it currently supports doing the weighting in the way shown here.  

I'll open an issue over there and see what we can do.

2024-08-05 17:05 UTC, kafitzgerald commented on examples/nblibrary/atm/nmse_utils.py
> +def nmse(obs, mod):
This also looks like something we could potentially implement in geocat-comp.

2024-08-05 17:07 UTC, islasimpson commented on examples/nblibrary/atm/nmse_utils.py
> +def nmse(obs, mod):
Sounds good.  Let me know if you do because there are other parts to this where you can decompose the NMSE into different components.  That's not included here as I didn't have the time, but can do in the future.

2024-08-05 17:24 UTC, kafitzgerald commented on examples/nblibrary/atm/nmse_utils.py
> +def nmse(obs, mod):
Good to know.  Thanks!  Will keep you in the loop.

2024-08-05 19:28 UTC, TeaganKing commented on examples/nblibrary/atm/averaging_utils.py
> +def seasonal_climatology_weighted(dat):
Thank you for chiming in, @kafitzgerald ! Just adding a link to the [GeoCAT issue here](https://github.com/NCAR/geocat-comp/issues/636) for reference and will resolve this conversation since I don't expect immediate changes on this particular PR.

2024-08-05 20:23 UTC, kafitzgerald commented on examples/nblibrary/atm/nmse_utils.py
> +def nmse(obs, mod):
Linking to the open issue on geocat-comp: https://github.com/NCAR/geocat-comp/issues/637

2024-08-07 02:59 UTC, TeaganKing commented
<img width="608" alt="Screen Shot 2024-08-06 at 8 51 55 PM" src="https://github.com/user-attachments/assets/8019f668-1a03-44e4-9299-02ed02ca95e5">
This is now generating plots as expected with `cupid-run`! @mnlevy1981 this is ready for your re-review.

2024-08-07 21:01 UTC, mnlevy1981 commented
@TeaganKing can you do a `git pull` and make sure a38b0b0 works for you? If it does, I think this is ready to merge :)

2024-08-07 21:02 UTC, mnlevy1981 approved these changes

2024-08-07 22:58 UTC, TeaganKing commented
This all runs smoothly and looks good to me! Thanks for your work on this, Mike and Isla! Merging in now.

2024-08-07 22:58 UTC, merged