Documentation updates: contributor's guide, notebook name standardization, hiding code cells
NCAR/CUPiD pull request #147
Opened 2024-10-17 15:43 UTC by TeaganKing

This PR will address issues raised in #146, #96, and #60. The key items it addresses are as follows:
1. Provide documentation on how to hide code cells
2. Provide suggestions for notebook names
3. Move contributor's guide from wiki to documentation page
4. Link to contributor's guide in 'how to add notebooks' page
5. Update a few outdated links and clarify a few steps
6. Clarify instructions on pre-commit installation
7. Update PR checklist to make pre-commit clearer and remove irrelevant items

Still need to do:
- [x] Remove wiki contributor's guide once this is merged in
- [x] Check with CUPiD team that notebook naming suggestion is reasonable (will check in next meeting and can edit later, too)
- [x] Hide any additional cells in `key_metrics` examples that need hiding

* [x] Have you followed the guidelines in our [Contributor's Guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide) (including the `pre-commit` check)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Does your submission pass tests?
* [x] Have you lint your code locally prior to submission?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully tested your changes locally?

2024-10-17 15:45 UTC, TeaganKing commented
Here is a screenshot of the build that implements the current changes.

![Screen Shot 2024-10-17 at 9 29 41 AM](https://github.com/user-attachments/assets/aaaa4b48-1f58-4727-a2f3-698250ac9496)

2024-10-21 15:53 UTC, mnlevy1981 requested changes
This is a huge update for the documentation, and it looks great! A few small tweaks to think about, but overall 👍

2024-10-21 15:53 UTC, mnlevy1981 commented on docs/conf.py
> +for file in ["README.md", "NCAR_tips.md", "contributors.md", "Contributors_Guide.md"]:
Three things:

1. `Contributors_Guide.md` is in `docs/`, not `${CUPID_ROOT}/`, so I don't think it needs to be copied here.
2. Should we rename `contributors.md` -> `contributors_to_cupid.md` to match the name change in the rst file? (If so, the rst file needs to be updated to point to the new name of the markdown file). Similarly, do we want to rename `ContributorsGuide.rst` -> `Contributors_Guide.rst` to match the markdown file?
3. Getting off on a tangent here, but we should also stick to a convention about underscores and capitalization. Maybe it should be `contributors_guide.rst` and `contributors_guide.md`? Then `adding_notebooks_to_collection.md` as well?

2024-10-21 15:53 UTC, mnlevy1981 commented on docs/addingnotebookstocollection.md
> +8. Your collection can now be run and built with `cupid-run` and `cupid-build` as usual.
How about

> Your collection can now be run with `cupid-run`, and then the website can be built with `cupid-build`.

2024-10-21 15:53 UTC, mnlevy1981 commented on docs/addingnotebookstocollection.md
> +    * Title your notebook something descriptive. A recommended format is `<region>_<variable>_<metric>_<comparisons>.ipynb`; for instance, this might look like `Global_PSL_NMSE_compare_obs_lens.ipynb
Do you want to rename the two key metric notebooks to match this proposed convention? I don't think we have open PRs updating those existing notebooks, and then we can point other open PRs to this one when we suggest new file names

2024-10-21 15:53 UTC, mnlevy1981 commented on README.md
> +1. Run `pre-commit install` to configure `git` to automatically run `pre-commit` checks when you try to commit changes; the commit will only proceed if all checks pass. Note that CUPiD uses `pre-comm
Should we say something about `pre-commit` being available in the `(cupid-dev)` environment? I think we want to recommend doing all commits from `(cupid-dev)` so `pre-commit` doesn't need to be available in other environments (also, to avoid doing the one-time setup stage of `pre-commit` more than once)

2024-10-21 15:53 UTC, mnlevy1981 commented on docs/addingnotebookstocollection.md
> +    * Set up `pre-commit` to ensure that your code is properly formatted and linted. Running `pre-commit install` will configure `git` to automatically run the `pre-commit` checks when you try to com
similar comment as above, do we need to specify `(cupid-dev)` here? I don't know that it needs to be brought up every time `pre-commit` is written about, but I do want to mention it at least once. I think the README makes more sense than this page, but would be open to mentioning the environment here instead (or in both spots).

2024-10-21 16:35 UTC, TeaganKing commented on README.md
> +1. Run `pre-commit install` to configure `git` to automatically run `pre-commit` checks when you try to commit changes; the commit will only proceed if all checks pass. Note that CUPiD uses `pre-comm
I specified this and added some more details in the Contributors guide, too.

2024-10-21 16:35 UTC, TeaganKing commented on docs/addingnotebookstocollection.md
> +    * Title your notebook something descriptive. A recommended format is `<region>_<variable>_<metric>_<comparisons>.ipynb`; for instance, this might look like `Global_PSL_NMSE_compare_obs_lens.ipynb
Great idea

2024-10-21 16:36 UTC, TeaganKing commented on docs/conf.py
> +for file in ["README.md", "NCAR_tips.md", "contributors.md", "Contributors_Guide.md"]:
1. Thanks for noting this!
2. I had purposely named these different things (similarly to the existing .md and .rst files) since using the same name here seemed to result in sphinx warnings due to unclear references to duplicate filenames (with different extensions).

2024-10-21 16:49 UTC, TeaganKing commented on docs/conf.py
> +for file in ["README.md", "NCAR_tips.md", "contributors.md", "Contributors_Guide.md"]:
3. I adjusted the .rst files to use lower case and underscores, and the .md files to use camelcase and no underscores...

2024-10-21 17:08 UTC, TeaganKing commented
Thanks for these suggestions, @mnlevy1981 . FYI I also re-built and fixed a few links, and it is building properly. The documentation still looks the same as the above screenshot.

2024-10-21 17:36 UTC, mnlevy1981 approved these changes
LGTM!

2024-10-21 17:41 UTC, merged