point to shared directory, no dask
NCAR/CUPiD pull request #49
Opened 2024-01-18 19:18 UTC by wwieder

hopefully improves availability for users

2024-01-18 21:38 UTC, mnlevy1981 requested changes
A few minor suggestions, but overall I think this is great -- the land notebook ran for me while the daskified version hung due to the hard-coded project key.

2024-01-18 21:38 UTC, mnlevy1981 commented on examples/nblibrary/land_comparision.ipynb
> +   "id": "2fd07a40-172e-435e-84e9-e422ae920220",
If it works without these cells, can we delete them instead of leaving them raw?

2024-01-18 21:38 UTC, mnlevy1981 commented on examples/nblibrary/land_comparision.ipynb
> +   "id": "e6c2ec6c-628c-4b0a-bb00-a2739422b4d8",
Same as above... if it works without these cells, can we delete them instead of leaving them raw?

2024-01-18 21:42 UTC, wwieder commented on README.md
> +4. type `firefox CUPiD/examples/coupled_model/computed_notebooks/quick-run/_build/html/index.html`, assuming your CUPiD is in your home directory
I'm also not sure where this should go, but  I was trying to remove frustrations of new users wondering what they had done after building their webpage.

2024-01-18 21:44 UTC, wwieder commented on README.md
> +4. type `firefox CUPiD/examples/coupled_model/computed_notebooks/quick-run/_build/html/index.html`, assuming your CUPiD is in your home directory
See if changes to readme reflect your ideas, @mnlevy1981 .

2024-01-18 21:49 UTC, mnlevy1981 commented
Also, the descriptive text at the top of the notebook says "calcultes 20 year mean" -- can you change this to "calculates 5 year mean"? (add the "a" to calculates, and change the 20 to 5)

2024-01-18 21:53 UTC, mnlevy1981 commented on README.md
> +4. type `firefox CUPiD/examples/coupled_model/computed_notebooks/quick-run/_build/html/index.html`
I was playing with this, and it looks like when you just start typing to run a command, (a) you can't copy / paste from your local machine's clipboard, and (b) it's really easy to lose the command if you switch tabs to see what you're supposed to type. It might be easier to replace this last step with

4. type `xterm` and hit enter to launch a terminal window
5. in the terminal, run `cd /path/to/CUPiD/examples/coupled_model/computed_notebooks/quick-run/_build/html/index.html`
6. run `firefox index.html &`

2024-01-18 21:53 UTC, mnlevy1981 commented on README.md
> +4. type `firefox CUPiD/examples/coupled_model/computed_notebooks/quick-run/_build/html/index.html`
sorry, first pass included `index.html` in the `cd` command, which is not a good idea

2024-01-18 21:55 UTC, wwieder commented on README.md
> +4. type `firefox CUPiD/examples/coupled_model/computed_notebooks/quick-run/_build/html/index.html`
Do you want to make this change?

2024-01-18 21:55 UTC, mnlevy1981 commented on README.md
> +4. type `firefox CUPiD/examples/coupled_model/computed_notebooks/quick-run/_build/html/index.html`, assuming your CUPiD is in your home directory
I think I was typing in a different tab, but I did have one more suggestion below (having users launch a terminal and then run `firefox` from the terminal will probably be less frustrating since they don't need to type in a long path in a temporary window).

2024-01-18 21:57 UTC, mnlevy1981 commented on README.md
> +4. type `firefox CUPiD/examples/coupled_model/computed_notebooks/quick-run/_build/html/index.html`
yeah, I think replacing [4] with [4], [5], [6] above is good; the second comment was just because I needed to edit the first comment due to a typo in [5]

2024-01-19 16:52 UTC, mnlevy1981 commented
@wwieder it looks like I can push changes to your branch -- do you want me to add one more commit with my changes to the README and removing the raw cells from the notebook? Also, I noticed you have a section header

> Big blob of passive C with depth in pAD

 With two empty cells below it. Are you planning to add a few more computations, or can we remove this section / the empty cells?

2024-01-19 19:05 UTC, wwieder commented
yes, you can commit the readme changes. it's also fine to reduce that
header at the end of the notebook.

On Fri, Jan 19, 2024 at 9:52 AM Michael Levy ***@***.***>
wrote:

> @wwieder <https://github.com/wwieder> it looks like I can push changes to
> your branch -- do you want me to add one more commit with my changes to the
> README and removing the raw cells from the notebook? Also, I noticed you
> have a section header
>
> Big blob of passive C with depth in pAD
>
> With two empty cells below it. Are you planning to add a few more
> computations, or can we remove this section / the empty cells?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NCAR/CUPiD/pull/49#issuecomment-1900757912>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB5IWJAB3R4N2DRUIDKS25LYPKQFJAVCNFSM6AAAAABCAZVHH6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBQG42TOOJRGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-19 21:24 UTC, merged