Simple instructions in documentation
NCAR/CUPiD pull request #62
Opened 2024-02-14 22:34 UTC by rmshkv

Adding a first draft of instructions for making a notebook CUPiD-compatible

2024-02-15 19:35 UTC, rmshkv commented on docs/addingnotebookstocollection.md
> +4. Open `config.yml`. First, add your new notebook (as its name, minus the `.ipynb`) to the list of notebooks that will be computed (`compute_notebooks`). For example:
If we're using the serial executor, they get executed in order, so if there are dependencies between the notebooks that does matter. There's also the option to explicitly group things under headings in the Jupyter book table of contents (which I didn't go into a ton of detail on for this doc to not overwhelm people), but that doesn't affect notebook execution, just how the book looks.

2024-02-15 19:42 UTC, rmshkv commented on docs/addingnotebookstocollection.md
> +6. If you'd like your new notebook included in the final Jupyter Book, add it to the Jupyter Book table of contents (`book_toc`). See [Jupyter Book's documentation](https://jupyterbook.org/en/stable/
Maybe better to include that on a separate page, if we're trying to keep this a very minimal how to make your notebook compatible sort of thing?

2024-02-15 19:53 UTC, rmshkv commented
The readme PR is going to create additional conflicts in index.rst - we should merge that first so we can resolve them here

2024-02-15 19:59 UTC, TeaganKing commented on docs/addingnotebookstocollection.md
> +6. If you'd like your new notebook included in the final Jupyter Book, add it to the Jupyter Book table of contents (`book_toc`). See [Jupyter Book's documentation](https://jupyterbook.org/en/stable/
Ok, seems reasonable!

2024-02-15 20:00 UTC, TeaganKing commented on docs/addingnotebookstocollection.md
> +4. Open `config.yml`. First, add your new notebook (as its name, minus the `.ipynb`) to the list of notebooks that will be computed (`compute_notebooks`). For example:
Got it. Since dependencies between notebooks will hopefully be a somewhat uncommon case, that seems fine to leave out and avoid overwhelming people.

2024-02-15 20:01 UTC, rmshkv commented on docs/addingnotebookstocollection.md
> +4. Open `config.yml`. First, add your new notebook (as its name, minus the `.ipynb`) to the list of notebooks that will be computed (`compute_notebooks`). For example:
I did add a quick note about execution order in the most recent commit to clarify that!

2024-02-15 20:06 UTC, TeaganKing commented on docs/addingnotebookstocollection.md
> +4. Open `config.yml`. First, add your new notebook (as its name, minus the `.ipynb`) to the list of notebooks that will be computed (`compute_notebooks`). For example:
I see! Looks good!

2024-02-21 17:21 UTC, mnlevy1981 requested changes
This all looks great, we just need to resolve the conflict in `index.rst` now that #65 has been merged

2024-02-21 17:33 UTC, merged