Add single-variable time series file generation function from ADF
NCAR/CUPiD pull request #78
Opened 2024-03-06 22:44 UTC by nusbaume

This should hopefully generalize the timeseries generation capability so that any CUPiD script or notebook can use it.

2024-03-06 22:50 UTC, TeaganKing commented on cupid/timeseries.py
> +        if "lev" in hist_file_ds:
Maybe adjust 'lev' if using cam vs clm, etc. Or pre-process files?

2024-03-06 22:52 UTC, TeaganKing commented on cupid/timeseries.py
> +    """
If we want to process all of the variables, it would be nice to have a 'process-all' Boolean parameter to control that.

2024-03-06 23:01 UTC, TeaganKing commented on cupid/timeseries.py
> +    res = self.variable_defaults
We will need to update `self`

2024-03-06 23:03 UTC, TeaganKing commented on cupid/timeseries.py
> +    res = self.variable_defaults
General cupid utility functions that would be useful may include `derive_variable`, etc

2024-03-06 23:07 UTC, wwieder commented on cupid/timeseries.py
> +        if "lev" in hist_file_ds:
this may be abstract enough to get the clm coordinate dimensions of levsoi levgrnd, levdcmp, levurb, levlak, etc?  I wonder if a more generic approach may be to copy all the coordinate dimensions from a history file onto the single variable time series?

2024-03-06 23:12 UTC, wwieder commented on cupid/timeseries.py
> +         CESM history number, ie h0, h1, etc.
Is this generic enough for different history file types (e.g. patch or landunit level output from CLM, as opposed to grid cell averages)

2024-03-07 17:49 UTC, TeaganKing commented on cupid/timeseries.py
> +    res = self.variable_defaults
Currently ADF uses a yaml file to define the variable defaults. Since variables will be different across components, we should probably have a similar default var yaml file for each component and create a CUPiD utility to load that similarly to the utility in [ADF's adf_obs](https://github.com/NCAR/ADF/blob/b96152255f7d386de34587eb8ed389f17db485b3/lib/adf_obs.py#L73).

2024-03-07 17:52 UTC, TeaganKing commented on cupid/timeseries.py
> +            self.end_diag_fail(emsg)
We could implement a common utility similar to ADF's [end_diag_fail](https://github.com/NCAR/ADF/blob/b96152255f7d386de34587eb8ed389f17db485b3/lib/adf_base.py#L71). We should determine whether we want just a single component to exit or the entire CUPiD process to exit.

2024-03-07 17:53 UTC, TeaganKing commented on cupid/timeseries.py
> +        with mp.Pool(processes=self.num_procs) as mpool:
Maybe we can just pass num_procs to the timeseries function as a parameter

2024-03-07 17:56 UTC, TeaganKing commented on cupid/timeseries.py
> +            self.derive_variables(
In ADF, this is defined [here](https://github.com/NCAR/ADF/blob/b96152255f7d386de34587eb8ed389f17db485b3/lib/adf_diag.py#L1011). This will be component-specific but we can pull out some common utility.

2024-03-12 21:20 UTC, TeaganKing commented on cupid/timeseries.py
> +    res = self.variable_defaults
We can add a list of variables to the `config.yaml` file for each component under a `timeseries` key.

2024-03-12 21:21 UTC, TeaganKing commented
We should implement this by adding a call to `run.py` under `if time_series`.

2024-03-12 22:09 UTC, nusbaume commented on cupid/timeseries.py
> +            self.derive_variables(
Just wanted to call attention to a draft PR @justin-richling opened in the ADF here:

https://github.com/NCAR/ADF/pull/278

It seems like we could potentially use the `sympy` package to allow users to write their own equations for derived variables without having to write new python code for each individual derived quantity.  Of course we haven't fully tested it yet so not sure if there are any dealbreakers, and it would bring in another few python packages to the conda environment.  Still, just wanted to give folks a heads up in case this seems like a feasible path forward for CUPiD.

2024-03-13 02:45 UTC, TeaganKing commented on cupid/timeseries.py
> +            self.derive_variables(
Thanks for mentioning this here! That seems like it could be really useful for allowing derived variables from each component!

2024-03-13 02:49 UTC, TeaganKing commented on cupid/timeseries.py
> +    """
We can do this via the `diag_var_list` argument, which will pull from the `config.yaml` file.

2024-03-13 02:51 UTC, TeaganKing commented on cupid/timeseries.py
> +    res = self.variable_defaults
The details used for plotting seem to be ADF-specific, so after discussion with @mnlevy1981 , we're thinking that we can just supply a list of variables to the `config.yaml` file instead of adding new `.yaml` files with lots of extra details.

2024-03-13 16:08 UTC, dabail10 commented
Is this ready for testing?

2024-03-13 21:08 UTC, TeaganKing commented
> Is this ready for testing?

Hi @dabail10 , sorry for the slow response, I'm in full-day training every day this week... I'm hoping to, at the least, wrap this up before our meeting next week, and will remove the draft label once it's ready for testing/review.

2024-03-18 21:55 UTC, TeaganKing commented
I've added the general infrastructure for components to use this timeseries generation. Each component will need to adjust the variables they want to generate (unless processing all vars) and the relevant history string (h0 is the current default) in `config.yml`. Additionally, in `run.py`, each component will need to update the height dimension they are using ('lev' is currently the default); this is in run.py instead of the config file since I don't anticipate it changing/needing to be modified by users.

2024-03-18 22:09 UTC, TeaganKing commented on cupid/timeseries.py
> +         CESM history number, ie h0, h1, etc.
@wwieder Are you referring to the hist_str here? This is now an editable quantity in the config.yml file. Would that be sufficient for those other kinds of history file output? I'm not familiar with those kinds of output, so any clarification would be helpful.

2024-03-18 22:12 UTC, TeaganKing commented on cupid/timeseries.py
> +        if "lev" in hist_file_ds:
This has been moved to a new issue (#86) so that we can try to get this functionality merged in.

2024-03-18 22:13 UTC, TeaganKing commented on cupid/timeseries.py
> +            self.derive_variables(
I mentioned this in a new issue (#86) so that we can keep the possibility of using `sympy` in mind going forward

2024-03-20 16:30 UTC, mnlevy1981 requested changes
This first set of comments is just from reading through the changes to `run.py` and `config.yml`; I'll take a closer look at `timeseries.py` and actually run the branch later today

2024-03-20 16:30 UTC, mnlevy1981 commented on cupid/run.py
> +                print(exc)
Should the `if time_series:` block get moved to after the

```py3
    # Get control structure
    control = cupid.util.get_control_dict(config_path)
    cupid.util.setup_book(config_path)
```

Then we'll only process the YAML file once. (Also, you can remove the `import sys` and `sys.tracebacklimit = 0` lines, I only included them to make the `NotImplementedError` exception easier to read)

2024-03-20 16:30 UTC, mnlevy1981 commented on cupid/run.py
> +        print("calling cam timeseries generation")
The rest of the print statements reference the general component, not the model itself (`lnd` instead of `clm`, `ocn` instead of `mom6`); I think you want `calling atm timeseries generation` here

2024-03-20 16:30 UTC, mnlevy1981 commented on cupid/run.py
> +        print("calling cice timeseries generation")
`ice` instead of `cice`?

2024-03-20 16:30 UTC, mnlevy1981 commented on examples/coupled_model/config.yml
> +  cice_end_years: [102]
`ice_*` instead of `cice_*` (and `derive_vars_ice` instead of `derive_vars_cice`)?

2024-03-20 16:55 UTC, TeaganKing commented on examples/coupled_model/config.yml
> +  cice_end_years: [102]
Making a new commit to address this...

2024-03-20 16:57 UTC, TeaganKing commented on cupid/run.py
> +        print("calling cam timeseries generation")
Done!

2024-03-20 16:58 UTC, TeaganKing commented
Thanks for those suggestions, @mnlevy1981 ! All of those comments have been addressed.

2024-03-20 19:48 UTC, mnlevy1981 requested changes
I'll run this branch before the 3:00 CUPiD meeting, but these are two more comments from just looking through the code

2024-03-20 19:48 UTC, mnlevy1981 commented on examples/coupled_model/config.yml
> +  num_procs: 8
Ideally we can determine `num_procs` the same way `dask` does when spinning up a `LocalCluster`, but for now can the default be 12 to match the recommendation in the [NCAR tips](https://ncar.github.io/CUPiD/NCARtips.html)

2024-03-20 19:48 UTC, mnlevy1981 commented on cupid/timeseries.py
> +        if not serial:  # if not serial
This could be an `else:`

2024-03-20 19:49 UTC, TeaganKing commented on examples/coupled_model/config.yml
> +  num_procs: 8
See #86

2024-03-20 20:25 UTC, mnlevy1981 commented on cupid/run.py
> +        )
Could this block be replaced with a loop?

```py3
for component in ['atm', 'ocn', 'lnd', 'ice', 'glc']:
        print(f"calling {component} timeseries generation")
        cupid.timeseries.create_time_series(
            component,
            timeseries_params[f"{component}_vars"],
            timeseries_params[f"derive_vars_{component}"],
            [timeseries_params["case_name"]],  # could also grab from compute_notebooks section of config file
            timeseries_params[f"{component}_hist_str"],
            [global_params["CESM_output_dir"] + "/" + timeseries_params["case_name"] + f"/{component}/hist/"],  # could also grab from compute_notebooks section of config file
            [global_params["CESM_output_dir"]+'/'+timeseries_params['case_name']+f'/{component}/proc/tseries/'],
            # Note that timeseries output will eventually go in /glade/derecho/scratch/${USER}/archive/${CASE}/${component}/proc/tseries/
            timeseries_params["ts_done"],
            timeseries_params["overwrite_ts"],
            timeseries_params[f"{component}_start_years"],  # could get from yaml file in adf_quick_run.parameter_groups.none.config_fil_str, or for other notebooks config files, eg ocean_surface.parameter_gropus.none.mom6_tools_config.start_date
            timeseries_params[f"{component}_end_years"],  # could get from yaml file in adf_quick_run.parameter_groups.none.config_fil_str, or for other notebooks config files, eg ocean_surface.parameter_gropus.none.mom6_tools_config.end_date
            "lev", # TODO: glc group will need to change this!
            num_procs,
            serial,
        )
```

It looks like we need to create a dictionary of vertical coordinates so we can do

```diff
- "lev", # TODO: glc group will need to change this!
+ vert_dim_name[component],
```

2024-03-20 20:28 UTC, mnlevy1981 requested changes
Could we update `README.md` to mention the ability to generate time series files? Relatedly -- when I ran this myself, I didn't have the `nco` module loaded so I got an error

```
FileNotFoundError: [Errno 2] No such file or directory: 'ncrcat'
```

Maybe a quick note in the README that time series generation requires NCO? Or can we install NCO via conda? if so, maybe we should just add it to conda-dev?

2024-03-20 20:33 UTC, kafitzgerald commented
You can certainly install it via [conda](https://anaconda.org/conda-forge/nco), but I'm not sure if there are advantages to using the module(s) available on HPC.  Potentially some performance / compatibility tradeoffs there.

2024-03-20 20:36 UTC, TeaganKing commented on cupid/run.py
> +        )
I also updated a few places where this expects 'cam' instead of 'atm' for consistency (but left checks for eg cam in hist files)

2024-03-20 20:45 UTC, TeaganKing commented
Ok, I added another note to #86 to investigate any potential tradeoffs with NCO, as well as made a note in the README.

And thanks for the loop suggestion Mike-- definitely a good idea!

2024-03-20 20:48 UTC, TeaganKing commented
I also updated the project vision as I was looking at the README anyways...

2024-03-20 22:22 UTC, rmshkv commented
To elaborate on something I mentioned in https://github.com/NCAR/CUPiD/pull/88 - a potential suggestion (that we definitely don't have to take, definitely backseat driving a bit here): the CUPiD/ploomber framework is already set up to support multiple phases of tasks that depend on each other, e.g. running timeseries generation first before diagnostics. I would encourage at some point moving the timeseries config block to be under `compute_scripts` in `config.yml`, which is already set up to be organized by components that can be turned on or off, and parameters specific to each component that can be passed in to a universal script. This keeps things more generalizable and less hard-coded. We could then use options in ploomber's tasks to specify that timeseries should be run first. Before that happens we need to document the script functionality (which I'll do soon :) ) and maybe build it out a little more, but after that I'd be happy to make a draft of that modification and see if it's something we want to go with.

2024-03-21 16:39 UTC, TeaganKing commented
> To elaborate on something I mentioned in #88 - a potential suggestion (that we don't have to take, definitely backseat driving a bit here): the CUPiD/ploomber framework is already set up to support multiple phases of tasks that depend on each other, e.g. running timeseries generation first before diagnostics. I would encourage at some point moving the timeseries config block to be under `compute_scripts` in `config.yml`, which is already set up to be organized by components that can be turned on or off, and parameters specific to each component that can be passed in to a universal script. This keeps things more generalizable and less hard-coded. We could then use options in ploomber's tasks to specify that timeseries should be run first. Before that happens we need to document the script functionality (which I'll do soon :) ) and maybe build it out a little more, but after that I'd be happy to make a draft of that modification and see if it's something we want to go with.

@rmshkv thanks for this suggestion! Just to clarify, are you suggesting creating a new `compute_scripts` block? I don't see a pre-existing one. Also, maybe it would be best to do this after #88 comes in? I think it would be a fairly simple change to move these and adjust how things are called from the config file in run.py, but I'm a bit hesitant to do that _before_ #88 comes in.

2024-03-21 16:49 UTC, TeaganKing commented on cupid/timeseries.py
> +         CESM history number, ie h0, h1, etc.
Also mentioned in #86 ...

2024-03-21 17:38 UTC, rmshkv commented
> > To elaborate on something I mentioned in #88 - a potential suggestion (that we don't have to take, definitely backseat driving a bit here): the CUPiD/ploomber framework is already set up to support multiple phases of tasks that depend on each other, e.g. running timeseries generation first before diagnostics. I would encourage at some point moving the timeseries config block to be under `compute_scripts` in `config.yml`, which is already set up to be organized by components that can be turned on or off, and parameters specific to each component that can be passed in to a universal script. This keeps things more generalizable and less hard-coded. We could then use options in ploomber's tasks to specify that timeseries should be run first. Before that happens we need to document the script functionality (which I'll do soon :) ) and maybe build it out a little more, but after that I'd be happy to make a draft of that modification and see if it's something we want to go with.
> 
> @rmshkv thanks for this suggestion! Just to clarify, are you suggesting creating a new `compute_scripts` block? I don't see a pre-existing one (although I do see `compute_notebooks`). Also, maybe it would be best to do this after #88 comes in? I think it would be a fairly simple change to move these and adjust how things are called from the config file in run.py, but I'm a bit hesitant to do that _before_ #88 comes in.

The functionality to handle a `compute_scripts` block provided by `config.yml` already fully exists - there just isn't a `compute_scripts` block in the existing example in this repo. That's why I need to document it, it's kind of a secret feature right now :) And yeah agreed that this and #88 should be merged in first - I just wanted to get my thoughts written down somewhere so we can discuss.

2024-03-21 17:45 UTC, TeaganKing commented
@rmshkv Got it, that makes sense now! Thank you for clarifying! It seems like your suggestion is probably the best way forward, but I summarized this and some other relevant discussions that Mike and I had in #86 (with a note that we should probably use `compute_scripts`) just so the information is all in one place.

2024-03-22 15:45 UTC, mnlevy1981 requested changes
This looks great! One more minor-ish suggestion, broken into two inline comments (and if we want to push it to #86 that's okay).

2024-03-22 15:45 UTC, mnlevy1981 commented on examples/coupled_model/config.yml
> +  atm_level: 'lev'
Should the component-specific blocks use common variable names? E.g.

```yaml
atm:
  vars: ['ACTNI', 'ACTNL', 'ACTREI','ACTREL','AODDUST']
  derive_vars: [] # {'PRECT':['PRECL','PRECC'], 'RESTOM':['FLNT','FSNT']}
  hist_str: 'h0'
  start_years: [2]
  end_years: [102]
  level: 'lev'

lnd:
  vars: ['ALTMAX', 'COST_NACTIVE', 'DENIT', 'EFLX_DYNBAL']  #['process_all']
  derive_vars: []
  hist_str: 'h0'
  start_years: [2]
  end_years: [102]
  level: 'lev'
```

This would probably clean up the call to `cupid.timeseries.create_time_series()` because we could replace a bunch of individual variables with `**timeseries_params[component]`. I think it would also be more in line with what @rmshkv has been working on in #88

2024-03-22 15:45 UTC, mnlevy1981 commented on cupid/run.py
> +        )
Per my other comment from the review, I think it would be helpful to make the call here with named arguments

```py3
            cupid.timeseries.create_time_series(
            component=component,
            diag_var_list=timeseries_params[f"{component}_vars"],
            derive_vars=timeseries_params[f"derive_vars_{component}"],
            case_names=[timeseries_params["case_name"]],  # could also grab from compute_notebooks section of config file
```

Because then we could replace a bunch of the named arguments with `**time_series_params["component"]`

2024-03-22 15:47 UTC, mnlevy1981 commented on examples/coupled_model/config.yml
> +  atm_level: 'lev'
note that these keys would need to match the arguments expected in `create_time_series`, so `vars` would become `diag_var_list` (or the argument name could change in `timeseries.py`). I didn't look closely at each key in this dictionary, some others may need to change as well

2024-03-22 17:43 UTC, TeaganKing commented on cupid/run.py
> +        )
This suggestion was moved to #86

2024-03-22 17:43 UTC, TeaganKing commented on examples/coupled_model/config.yml
> +  atm_level: 'lev'
The component-specific and standard var names are now implemented; thanks for the suggestion!

2024-03-22 18:02 UTC, mnlevy1981 commented on examples/coupled_model/config.yml
> +    hist_str: 'h'
this should be `h.frc` to find the MOM6 history file with `taux` and `tauy`.

Also, one more thing for #86: MOM6 splits variables across a larger number of history files than other components, so at some point we may need to support `hist_str` being a list (which probably requires renaming it, since it's no longer required to be a `str`).

2024-03-22 18:48 UTC, mnlevy1981 approved these changes
Looks good, great work!

2024-03-22 18:49 UTC, TeaganKing commented
Thanks for all your help and suggestions from everyone who commented!

2024-03-22 18:49 UTC, merged