API updates to specify components
NCAR/CUPiD pull request #88
Opened 2024-03-19 22:21 UTC by rmshkv

Addresses https://github.com/NCAR/CUPiD/issues/63.

This adds a layer of keys in `config.yml` that group notebooks (and scripts) by ESM component, e.g. `atmosphere`, `ocean`, etc. These keys are referenced by flags that can be passed in to `cupid-run`, e.g. `-atm`, `-ocn`, etc., as specified in the README. If no component flags are passed in, all components are run. This can also be done explicitly by using `--all` or `-a`.

This update also prompted changes to how we're managing the environment (kernel) checking step that was being done by `util.get_control_dict()` called by `cupid-run`. We still check the existence of all environments specified in `config.yml` (regardless of whether that component is turned on by flags), but just raise a warning if the environment does not exist. If that notebook is specified to be run, another warning is raised and that notebook is not run, but the others still are. Also, if neither a `default_kernel_name`nor a notebook-specific `kernel_name` is provided, `cupid-analysis` is assumed and another warning is raised.

2024-03-19 22:31 UTC, rmshkv commented
Also, I don't love how the warnings show up currently, you end up with a large block of text mixed in with all the Ploomber stuff and also the  `warnings.warn()`... code used to generate the warnings gets printed out too. Please feel free to propose a better way if you know one!

2024-03-19 22:35 UTC, TeaganKing commented
Hi @rmshkv , I'll look at this PR in more detail, but wanted to post a quick note as I am realizing that there will probably be some conflicts between this PR and #78. I think that's fine, and I can update #78 if this comes in first. We may also want to discuss whether the component flags also result in timeseries being run for only the specified components (eg, if you run `cupid-run config.yml -ts -atm`, that would generate timeseries and run the notebooks for `atm` only). I think this may be ideal and still seems clear to me, but I'm open to other thoughts there.

2024-03-19 22:49 UTC, rmshkv commented
> Hi @rmshkv , I'll look at this PR in more detail, but wanted to post a quick note as I am realizing that there will probably be some conflicts between this PR and #78. I think that's fine, and I can update #78 if this comes in first. We may also want to discuss whether the component flags also result in timeseries being run for only the specified components (eg, if you run `cupid-run config.yml -ts -atm`, that would generate timeseries and run the notebooks for `atm` only). I think this may be ideal and still seems clear to me, but I'm open to other thoughts there.

Ah thanks for the heads up, I didn't realize how far along the timeseries generation work was! I think there are several different ways we could integrate these features...potentially even something like including the timeseries generation code for each component under `compute_scripts`, which already get turned on or off by the component flags but could then also be affected by the `-ts` flag? Maybe we can chat about it at the meeting tomorrow.

2024-03-19 22:51 UTC, TeaganKing reviewed
I generally approve these updates; but yes, let's talk more about the `ts` integration tomorrow too!

2024-03-19 22:51 UTC, TeaganKing commented on cupid/run.py
> +    if True not in [atmosphere, ocean, land, seaice, landice]:
Seems like a good default option!

2024-03-19 22:51 UTC, TeaganKing commented on cupid/run.py
> +                warnings.warn(f"Environment {bad_env} specified for {script}.py could not be found; {script}.py will not be run.")
Super minor, but would it be useful to suggest checking the README for installation instructions here? It may be obvious, but could potentially help some users.

2024-03-19 22:51 UTC, TeaganKing commented on examples/coupled_model/config.yml
> +      seaice:
This structure is a lot clearer with your changes!

We may want to encourage names for notebooks that are slightly different from the component name (eg, `seaice` listed twice here is confusing). Perhaps this is beyond the scope of this PR, but I wonder if down the line it may be useful to have some standard notebook names (eg, obs comparisons, basic diagnostics, etc) across components...

2024-03-27 20:15 UTC, mnlevy1981 requested changes
I've noted a handful of small changes that would help clean things up a bit, and I also have a bigger request: could we create subdirectories in `examples/nblibrary` to match the new `compute_notebook` keys and move the appropriate notebooks in? This would potentially lead to some minor tweaks in the file name itself... So

```
index.ipynb -> infrastructure/index.ipynb
adf_quick_run.ipynb -> atmosphere/quick_run.ipynb
ocean_surface.ipynb -> surface_plots.ipynb
land_comparison.ipynb -> comparison_plots.ipynb
seaice.ipynb -> seaice/[something descriptive].ipynb
```

We would need JupyterBook to respect this directory structure; maybe `infrastructure/index.ipynb -> index.html` is a special case, but we'd want `ocean/surface_plots.html` in case other components also want to have a `surface_plots.ipynb` notebook.

2024-03-27 20:15 UTC, mnlevy1981 commented on cupid/util.py
> +            env_check[info["kernel_name"]] = None
Can we do the

```py3
env_check[info["kernel_name"]] = info["kernel_name"] in jupyter_client.kernelspec.find_kernel_specs()
```

right away instead of looping through the `env_check` keys later? Maybe something like

```py3
if info["kernel_name"] not in env_check:
  env_check[info["kernel_name"]] = info["kernel_name"] in jupyter_client.kernelspec.find_kernel_specs()
```

to avoid checking for the same environment repeatedly?

2024-03-27 20:15 UTC, mnlevy1981 commented on cupid/util.py
> +                        warnings.warn(f"No environment specified for {script}.py; assuming cupid-analysis environment.")
Same comment as in the `control["compute_notebooks"]` loop above

2024-03-27 20:15 UTC, mnlevy1981 commented on cupid/util.py
> +        env_check[environment] = environment in jupyter_client.kernelspec.find_kernel_specs()
Same comment as in the `control["compute_notebooks"]` loop above (setting `env_check` in 47 and 58 means we don't need the loop at 60 and 61)

2024-03-27 20:15 UTC, mnlevy1981 commented on cupid/util.py
> +    control["env_check"] = env_check
With the comments above, we can likely get rid of the local `env_check` and just populate `control["env_check"][info["kernel_name"]]`:

```py3
if info["kernel_name"] not in control["env_check"]:
  control["env_check"][info["kernel_name"]] = info["kernel_name"] in jupyter_client.kernelspec.find_kernel_specs()
```

2024-03-27 20:15 UTC, mnlevy1981 commented on cupid/util.py
> +    for nb_category in control["compute_notebooks"].values():
For the `compute_scripts` block we have a

```py3
if "compute_scripts" in control:
```

do we need a similar

```py3
if "compute_notebooks" in control:
```

check here?

2024-04-02 23:27 UTC, rmshkv commented on cupid/util.py
> +    for nb_category in control["compute_notebooks"].values():
Originally I was assuming that every collection would have notebooks but that scripts were optional, hence this logic, but that isn't necessarily how people are going to use this. I'll add the extra logic where necessary.

2024-04-16 17:24 UTC, rmshkv commented on cupid/util.py
> -    # get toc files; ignore glob expressions
I commented out this whole block and think it would be fine to remove it - it seems like it's mostly additional checking that's handled fine by Jupyter Book itself, but I want some second opinions before I actually do that

2024-04-16 17:31 UTC, rmshkv commented on examples/coupled_model/config.yml
>  ########### JUPYTER BOOK CONFIG ###########
For the Jupyter book section, I went with explicitly specifying the path with the new folder for each one, rather than building in official handling for the "chapter caption" to match the directory structure. I think this keeps a bit more flexibility and makes it more explicit what the Jupyter book is doing (+ avoids an additional layer of hard-codey custom stuff), but we could choose to go the other way if we want.

2024-04-16 17:36 UTC, rmshkv commented on cupid/util.py
> -    # get toc files; ignore glob expressions
This also connects to more generally cleaning up setup_book as per https://github.com/NCAR/CUPiD/issues/36, but I'm going to save the rest of that for a different PR

2024-04-25 20:54 UTC, TeaganKing commented on examples/coupled_model/config.yml
> +      seaice:
Putting this into an issue #96

2024-04-25 22:28 UTC, TeaganKing approved these changes
Thanks for all your work on this, @rmshkv ! I ran through the notebooks and generated a jupyter book, and this all runs smoothly as far as I can tell.

I think the explicit path specification in the Jupyter Book Config seems clear, and that seems fine to me to remove that commented block that you mentioned.

2024-04-25 22:46 UTC, mnlevy1981 requested changes
I didn't make it very far through the code, and looking at my calendar I might not have time to come back to this until Tuesday... but I'll try to add more comments sooner than that

2024-04-25 22:46 UTC, mnlevy1981 commented on cupid/run.py
> +            all = True
Do we need a `--all` option if we are setting `all` here? What do want to have happen if a user runs `cupid-run --all --atmosphere config.yml`? If the answer is "a user shouldn't run with those options together", it makes more sense to drop `all` from `click` / the input argument list and just set

```py3
all = (True not in [atmosphere, ocean, land, seaice, landice])
```

2024-04-26 16:26 UTC, mnlevy1981 commented on cupid/run.py
> +                    all_nbs[nb]['output_dir'] = output_dir + '/' + comp_name
Does this need to be in an `if all` block? Could we do something like

```py3
for comp_name, comp_bool in component_options.items():
  if comp_name in control['compute_notebooks']) and (comp_bool or all):
    for nb, info in control['compute_notebooks'][comp_name].items():
      all_nbs[nb] = info
      all_nbs[nb]['nb_path_root'] = nb_path_root + '/' + comp_name
      all_nbs[nb]['output_dir'] = output_dir + '/' + comp_name
  elif comp_bool:
        warnings.warn(f"No notebooks for {comp_name} component specified in config file.")
```

to encompass both the `if all` and `else` portions of the existing code? I think this snippet behaves exactly like what you've written, but there's only one loop over `control['compute_notebooks'][comp_name]` to update if we change the `config.yml` schema again.

I haven't tested the above block, so you might need a small tweak but the logic in the `if` / `else` block should be sound.

2024-04-26 16:30 UTC, mnlevy1981 commented on cupid/run.py
> +            all = True
It looks we have an identical block of code in 142 / 143, but that's in an `if 'compute_notebooks' in control:` block and this is in `if "compute_scripts" in control:`. Could we move the first instance of this out of the if statement (maybe directly after defining `component_options`) and then remove this occurence?

2024-04-26 16:31 UTC, mnlevy1981 commented on cupid/run.py
> +        if all:
Same comment as the `compute_notebooks` block - let's reformulate the if checks and only have a single loop through `control['compute_scripts'][comp_name]`

2024-04-26 16:32 UTC, mnlevy1981 commented on cupid/util.py
> -    # get toc files; ignore glob expressions
It sure looks like the commented out code is un-necessary -- I vote for removing it altogether (if we realize we need it later, we can grab it from an old commit)

2024-04-26 16:34 UTC, mnlevy1981 commented
Most of my comments on this pass-through are related to reducing the amount of duplicated code. There is still a lot of similarities between `compute_notebooks` and `compute_scripts` sections, but cleaning that up is probably best left for a separate issue

2024-04-26 17:16 UTC, mnlevy1981 commented on cupid/run.py
> +                    all_nbs[nb]['output_dir'] = output_dir + '/' + comp_name
Now I'm second-guessing the logic. I think we really want

```py3
if comp_name in control['compute_notebooks']) and comp_bool:
  ...
elif comp_bool and not all:
  ...
```
So if `comp_bool` is true and the component has notebooks defined in control structure, add those to `all_nbs`. If `comp_bool and not all` then the user specified `--comp` but we're in the else block so the component name does not have notebooks defined in the control structure and that's when we want to warn about requesting a specific component that isn't in the config file.

2024-05-02 23:52 UTC, rmshkv commented
> Hi @rmshkv , I'll look at this PR in more detail, but wanted to post a quick note as I am realizing that there will probably be some conflicts between this PR and #78. I think that's fine, and I can update #78 if this comes in first. We may also want to discuss whether the component flags also result in timeseries being run for only the specified components (eg, if you run `cupid-run config.yml -ts -atm`, that would generate timeseries and run the notebooks for `atm` only). I think this may be ideal and still seems clear to me, but I'm open to other thoughts there.

I just implemented this (-ts and component flags will only run those components). There's a tiny bit of extra code because the timeseries block references components as "atm", "ocn", etc and the notebooks/scripts blocks reference them as "atmosphere", "ocean", etc but it works fine and we can address it later, in the interest of getting this PR in.

2024-05-02 23:56 UTC, rmshkv commented
> > Hi @rmshkv , I'll look at this PR in more detail, but wanted to post a quick note as I am realizing that there will probably be some conflicts between this PR and #78. I think that's fine, and I can update #78 if this comes in first. We may also want to discuss whether the component flags also result in timeseries being run for only the specified components (eg, if you run `cupid-run config.yml -ts -atm`, that would generate timeseries and run the notebooks for `atm` only). I think this may be ideal and still seems clear to me, but I'm open to other thoughts there.
> 
> I just implemented this (-ts and component flags will only run those components). There's a tiny bit of extra code because the timeseries block references components as "atm", "ocn", etc and the notebooks/scripts blocks reference them as "atmosphere", "ocean", etc but it works fine and we can address it later, in the interest of getting this PR in.

On second thought, maybe we do want them to match...I'll make everything use the short names, and we can change that later if we decide to.

2024-05-03 00:01 UTC, mnlevy1981 commented
> > > Hi @rmshkv , I'll look at this PR in more detail, but wanted to post a quick note as I am realizing that there will probably be some conflicts between this PR and #78. I think that's fine, and I can update #78 if this comes in first. We may also want to discuss whether the component flags also result in timeseries being run for only the specified components (eg, if you run `cupid-run config.yml -ts -atm`, that would generate timeseries and run the notebooks for `atm` only). I think this may be ideal and still seems clear to me, but I'm open to other thoughts there.
> > 
> > 
> > I just implemented this (-ts and component flags will only run those components). There's a tiny bit of extra code because the timeseries block references components as "atm", "ocn", etc and the notebooks/scripts blocks reference them as "atmosphere", "ocean", etc but it works fine and we can address it later, in the interest of getting this PR in.
> 
> On second thought, maybe we do want them to match...I'll make everything use the short names, and we can change that later if we decide to.

If you haven't made the change yet, I'd prefer changing the time series to use the longer names... but if you are already using the short names we can clean that up in a future PR :)

2024-05-03 00:08 UTC, rmshkv commented
> > > > Hi @rmshkv , I'll look at this PR in more detail, but wanted to post a quick note as I am realizing that there will probably be some conflicts between this PR and #78. I think that's fine, and I can update #78 if this comes in first. We may also want to discuss whether the component flags also result in timeseries being run for only the specified components (eg, if you run `cupid-run config.yml -ts -atm`, that would generate timeseries and run the notebooks for `atm` only). I think this may be ideal and still seems clear to me, but I'm open to other thoughts there.
> > > 
> > > 
> > > I just implemented this (-ts and component flags will only run those components). There's a tiny bit of extra code because the timeseries block references components as "atm", "ocn", etc and the notebooks/scripts blocks reference them as "atmosphere", "ocean", etc but it works fine and we can address it later, in the interest of getting this PR in.
> > 
> > 
> > On second thought, maybe we do want them to match...I'll make everything use the short names, and we can change that later if we decide to.
> 
> If you haven't made the change yet, I'd prefer changing the time series to use the longer names... but if you are already using the short names we can clean that up in a future PR :)

I made the change just a minute ago, but it's not too hard to change back later. I also prefer the long names for clarity, but I don't know much about what the timeseries code is doing and it looks like some of the directories it's creating might depend on the component shortname, so I didn't want to touch that myself.

2024-05-03 00:31 UTC, rmshkv commented
All right, I think that addresses everything requested! Feel free to run some tests again and let me know what you think.

2024-05-03 17:42 UTC, TeaganKing commented
> > > > > Hi @rmshkv , I'll look at this PR in more detail, but wanted to post a quick note as I am realizing that there will probably be some conflicts between this PR and #78. I think that's fine, and I can update #78 if this comes in first. We may also want to discuss whether the component flags also result in timeseries being run for only the specified components (eg, if you run `cupid-run config.yml -ts -atm`, that would generate timeseries and run the notebooks for `atm` only). I think this may be ideal and still seems clear to me, but I'm open to other thoughts there.
> > > > 
> > > > 
> > > > I just implemented this (-ts and component flags will only run those components). There's a tiny bit of extra code because the timeseries block references components as "atm", "ocn", etc and the notebooks/scripts blocks reference them as "atmosphere", "ocean", etc but it works fine and we can address it later, in the interest of getting this PR in.
> > > 
> > > 
> > > On second thought, maybe we do want them to match...I'll make everything use the short names, and we can change that later if we decide to.
> > 
> > 
> > If you haven't made the change yet, I'd prefer changing the time series to use the longer names... but if you are already using the short names we can clean that up in a future PR :)
> 
> I made the change just a minute ago, but it's not too hard to change back later. I also prefer the long names for clarity, but I don't know much about what the timeseries code is doing and it looks like some of the directories it's creating might depend on the component shortname, so I didn't want to touch that myself.

Just as an FYI, the time series code isn't super dependent on how the components are named; There's a comment in line 285 that would need to be updated, as well as just the names in lines 329, 52, and 232. I'm fine with keeping the short names for now, though.

2024-05-03 17:59 UTC, TeaganKing commented
All the tests I've run are looking good! I do also agree that updated the logic regarding 'all' is improved when the assumption is that 'all' is the default unless one component is specified, and a flag is not needed to specify 'all'. I think that the lack of a flag clarifies that 'all' is default instead of potential confusion with a default that can also be specified with a flag.

2024-05-03 19:43 UTC, mnlevy1981 commented
The code in `run.py` looks great and `cupid-run config.yml` generates output as expected, but `cupid-build` isn't getting the sidebar right anymore:

![cupid book](https://github.com/NCAR/CUPiD/assets/4297161/99da790b-2884-49d8-afcb-db06c974022a)

I was hoping the sidebar would have the name of all the components, and then links to each of the component's notebooks underneath.

I really like how this turned out:

```
(cupid-dev) examples/coupled_model$ cupid-run -atm -glc config.yml
/glade/work/mlevy/codes/CUPiD/cupid/run.py:152: UserWarning: No notebooks for glc component specified in config file.
```

(And `adf_quick_run.ipynb` was still executed).

2024-05-03 20:33 UTC, rmshkv commented
> The code in `run.py` looks great and `cupid-run config.yml` generates output as expected, but `cupid-build` isn't getting the sidebar right anymore:
> 
> ![cupid book](https://private-user-images.githubusercontent.com/4297161/327863395-99da790b-2884-49d8-afcb-db06c974022a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NjU3MTgsIm5iZiI6MTcxNDc2NTQxOCwicGF0aCI6Ii80Mjk3MTYxLzMyNzg2MzM5NS05OWRhNzkwYi0yODg0LTQ5ZDgtYWZjYi1kYjA2Yzk3NDAyMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMTk0MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZlNGIxZjM5OWQ0YjE1OGRkZTI5NTJhMmE3NDYwZGE5NDYzODE1ZjEzMzhiNWU0NWQ3M2U0ZDI2ZTJhNWJlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GJ09bylqXO6G7YvlgUU09MT-YelqkmSphlaFlzf6enU)
> 
> I was hoping the sidebar would have the name of all the components, and then links to each of the component's notebooks underneath.
> 
> I really like how this turned out:
> 
> ```
> (cupid-dev) examples/coupled_model$ cupid-run -atm -glc config.yml
> cupid/run.py:152: UserWarning: No notebooks for glc component specified in config file.
> ```
> 
> (And `adf_quick_run.ipynb` was still executed).

My bad, I just forgot to change the explicit paths in the jupyter book config with the new short folder names. Should be fixed now!

2024-05-03 21:45 UTC, mnlevy1981 commented
> My bad, I just forgot to change the explicit paths in the jupyter book config with the new short folder names. Should be fixed now!

After updating to f114b83 I needed to rerun `cupid-run` and `cupid-build`, but the page looks great now!

![cupid book 2](https://github.com/NCAR/CUPiD/assets/4297161/cc0be763-aca1-481d-aeec-b613d4a5a004)

2024-05-03 21:45 UTC, mnlevy1981 approved these changes

2024-05-03 21:45 UTC, merged