Some updated pylint and black formatting, added docstrings to improve clarity when adding to repo
NCAR/CUPiD pull request #94
Opened 2024-04-15 17:20 UTC by TeaganKing

Addresses #77 .

I'd also like to add in some testing that runs upon submitting PRs that runs pylint and black, so this will help get us closer to a clean run and make it easier for contributors to understand and add to code.

2024-05-07 16:22 UTC, TeaganKing commented
Docstrings have all been added, and this has been updated to not conflict with Lev's most recent PR. I also adjusted a few more pylint/black issues (there's still some outstanding ones, though).

2024-05-07 17:50 UTC, mnlevy1981 requested changes
Highlighting a few formatting changes from `black` or `flake` that seem questionable, and also suggesting a few changes to docstrings

2024-05-07 17:50 UTC, mnlevy1981 commented on cupid/run.py
> +"""
For consistency, I'd like this docstring to match the output of `cupid-run --help`. On `main` that currently looks like

```
Usage: cupid-run [OPTIONS] CONFIG_PATH

  Main engine to set up running all the notebooks.

Options:
  -s, --serial        Do not use LocalCluster objects
  -ts, --time-series  Run time series generation scripts prior to diagnostics
  -atm, --atmosphere  Run atmosphere component diagnostics
  -ocn, --ocean       Run ocean component diagnostics
  -lnd, --land        Run land component diagnostics
  -ice, --seaice      Run sea ice component diagnostics
  -glc, --landice     Run land ice component diagnostics
  -h, --help          Show this message and exit.
```

But I'd fully support modifying the `click` decorations and / or the docstring for `run()` to provide more detail. (E.g. getting click to describe `CONFIG_PATH` the way you've done here)

2024-05-07 17:50 UTC, mnlevy1981 commented on cupid/run.py
> +        for n_b, info in control["compute_notebooks"]["infrastructure"].items():
Same comment as with `ds`, let's see if we can get the formatters to accept `nb` as a valid variable name (or use `notebook`; `n_b` feels very awkward)

2024-05-07 17:50 UTC, mnlevy1981 commented on cupid/run.py
> +                all_nbs.pop(n_b)
If we do switch from `nb` -> `notebook`, lets also rename `all_nbs` -> `all_notebooks

2024-05-07 17:50 UTC, mnlevy1981 commented on cupid/util.py
> +class MdJinjaEngine(NBClientEngine):
@rmshkv -- do you know what `md_` stands for in this context?

We probably want this class to be `MDJinjaEngine`, though if the meaning of `MD` has been lost, I'm also okay with naming this class `JinjaEngine`

2024-05-07 17:50 UTC, mnlevy1981 commented on cupid/util.py
> +            for n_b, info in nb_category.items():
another `n_b` in a different file...

2024-05-07 18:29 UTC, TeaganKing commented on cupid/run.py
> +        for n_b, info in control["compute_notebooks"]["infrastructure"].items():
Ok, yup I agree!

2024-05-07 18:39 UTC, TeaganKing commented on cupid/run.py
> +"""
That works for me!

2024-05-07 18:40 UTC, TeaganKing commented on cupid/util.py
> +class MdJinjaEngine(NBClientEngine):
Does this stand for markdown?

2024-05-07 18:43 UTC, TeaganKing commented on cupid/run.py
> +                    ],  # could also grab from compute_notebooks section of config file
Right, I think that black keeps reformatting it this way... I did not do that one by hand. It does look a little confusing though. I'll make it more readable and add a "# fmt: off" and "on".

2024-05-07 19:15 UTC, TeaganKing commented on cupid/run.py
>  @click.argument("config_path")
Ok, I added a commit that I think addresses this; let me know if you envisioned something different.

2024-05-08 18:01 UTC, TeaganKing commented on cupid/run.py
>  @click.argument("config_path")
OK, I made those changes... However, I'm struggling to figure out why `cupid-build` is not working with a click argument.

When I run `cupid-build`, I get the following error:
```
Traceback (most recent call last):
  File "/glade/work/tking/conda-envs/cupid-dev/bin/cupid-build", line 8, in <module>
    sys.exit(build())
             ^^^^^^^
TypeError: build() missing 1 required positional argument: 'config_path'
```

Any thoughts on where this might be coming from? In `build.py`, there is a specification of the argument `config_path`, and I am not seeing where else in the code build is called that would cause this issue.

2024-05-08 18:14 UTC, TeaganKing commented on cupid/util.py
> +class MdJinjaEngine(NBClientEngine):
This is the bit related to markdown in this class:
```
for cell in nb_man.nb.cells:
    if cell.cell_type == "markdown":
        cell["source"] = Template(cell["source"]).render(**jinja_data)
```

I feel like we could probably get rid of the 'Md' since it seems like the main purpose is to act as a Jinja Engine with the caveat of not executing markdown cells, but that's not really the main functionality.

2024-05-08 18:38 UTC, TeaganKing commented on cupid/run.py
>  @click.argument("config_path")
I managed to get around this by specifying config_path as an argument instead of an option.

2024-05-08 18:38 UTC, rmshkv commented on cupid/util.py
> +class MdJinjaEngine(NBClientEngine):
Yeah that's a holdover from Matt and I think it stands for Markdown. What that does is it lets you do jinja templating in Markdown cells, so if for example you wanted the title of the notebook in a Markdown cell to depend on some var_to_plot parameter that you set, you could call it Plotting {{var_to_plot}} and that would get filled in in the executed notebook.

2024-05-08 18:43 UTC, TeaganKing commented on cupid/util.py
> +class MdJinjaEngine(NBClientEngine):
Ok, thanks for the clarification, I'll just write out MarkdownJinjaEngine then!

2024-05-08 20:31 UTC, mnlevy1981 requested changes
For `config_path`, `clear.py` and `run.py` are using `click.option()` but `build.py` is using `click.argument()`. I like using `click.argument()` more, it makes more sense to run `cupid-run some_other_config.yml` than `cupid-run --config-file some_other_config.yml` (and the `default=config.yml` argument is valid in both functions, so `cupid-run` can still default to `config.yml`). Can we update `clear.py` and `run.py` to use the argument, and then also update the docstrings to include

```
   Args:
        config_path: str, path to configuration file (default config.yml)

    Returns:
        None
```

like in `build.py`? Note that I added an extra line break between `Args` and `Returns` (and also changed `yml file` to `configuration file`); without the additional break, the `--help` argument runs those two lines together:

```
$ cupid-build --help
Usage: cupid-build [OPTIONS] [CONFIG_PATH]

  Build a Jupyter book based on the TOC in config.yml. Called by `cupid-
  build`.

  Args:     config_path: str, path to yml file (default config.yml) Returns:
  None

Options:
  --help  Show this message and exit.
```

This will trickle into `README.md` file as well

2024-05-08 22:07 UTC, TeaganKing commented
Thanks for your review, @mnlevy1981 ! I have updated `clear.py` and `run.py` to use the argument version instead of the option version, and related docstrings have also been updated.

2024-05-08 23:26 UTC, mnlevy1981 approved these changes
This looks great!

2024-05-08 23:26 UTC, merged