Include GitHub Actions
NCAR/CUPiD pull request #98
Opened 2024-05-09 16:24 UTC by TeaganKing

Closes #97

2024-05-16 15:34 UTC, TeaganKing commented
Ok pre-commits are now working properly and conflicts between black-jupyter and autopep8, as well as the double vs single quotes, are resolved (thanks to some suggestions from Anissa on the former!)

Anyways, this should be ready for review now.

2024-05-17 16:27 UTC, mnlevy1981 requested changes
I'm not sure of the best place for it (maybe the `README` for now, but eventually in a "developer's guide" type page?), but we should include instructions on how to enable `pre-commit` locally. The real power of the package is that it will warn you when you try to commit changes that violate the style guide; using it in Github Actions is more of a backup plan than anything else.

Other than that (and my confusion around `annotate`), this all looks great! Little is as satisfying as seeing a whole bunch of trailing whitespace get removed :)

2024-05-17 16:27 UTC, mnlevy1981 commented on docs/conf.py
> +from __future__ import annotations
It doesn't look like `annotations` is used anywhere; was this requested by something in the CI testing?

2024-05-17 16:27 UTC, mnlevy1981 commented on examples/nblibrary/ice/plot_diff.py
> +from __future__ import annotations
same comment; I assume it's getting added by the CI but I don't understand why

2024-05-17 16:42 UTC, TeaganKing commented
I added a note on running `pre-commit run` to our [contributor's guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide). If you prefer this goes in the readme, I could add it there too, but it seems to fit better in the wiki page (although perhaps it is a little hidden).

I think the `from __future__ import annotations` is needed for checking imports with `reorder-python-imports`, which is a bit annoying.

2024-05-17 16:53 UTC, mnlevy1981 approved these changes
> I added a note on running `pre-commit run` to our [contributor's guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide). If you prefer this goes in the readme, I could add it there too, but it seems to fit better in the wiki page (although perhaps it is a little hidden).

The contributor guide is a great place for it! I didn't think to look there, and the wiki files don't show up as changed in the PR :) I'll come back this afternoon with a small update (adding `precommit` to `environments/dev-environment.yml` and giving more explicit instructions in the wiki about setting it up to run with every `git commit`) but I'll merge this now

2024-05-17 16:53 UTC, merged

2024-05-17 16:59 UTC, TeaganKing commented
Sounds great! Thanks for reviewing and merging this, Mike!